## tomcat 配置
server:
  ## 监听端口
  port: 9292
  ## 服务配置
  tomcat:
    ## 超时时间
    connection-timeout: 10000

## Spring 配置
spring:
  ## 动态配置
  profiles:
    ## 状态
    active: dev
  # 路 径 匹 配 机 制
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  ## 邮件
  mail:
    ## 协议
    protocol: smtp
    ## 地址
    host: smtp.qq.com
    ## 端口
    port: 587
    ## 账户
    username: 854085467@qq.com
    ## 密钥
    password:
    ## 字符集
    default-encoding: UTF-8
    ## 测试
    test-connection: false
    ## 来源
    from: 854085467@qq.com

## mybatis 配置
mybatis-plus:
  ## 文件位置
  mapper-locations: classpath*:com/pearadmin/pro/modules/**/xml/**.xml
  ## 实体别名
  type-aliases-package: com.pearadmin
  ## 日志打印
  configuration:
    ## 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## Helper 配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## 阿里云 Oss 存储
aliyun:
  ## 对象存储
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: anything
    accessKeySecret: anything
    bucketName: pear-admin
  ## 短信发送
  sms:
    accessKeyId: anything
    accessKeySecret: anything
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    templateCode: template-name
    signName: sign-name